[package]
name = "game_of_life"
version = "0.1.0"
edition = "2024"

[dependencies]
glow = "0.18.0"
glutin = "0.32.3"
glutin-winit = "0.5.0"
gol-frontend = { workspace = true }

[workspace]
members = [
    "crates/gol-backend",
    "crates/gol-frontend"
]

[workspace.dependencies]
gol-backend = { path = "crates/gol-backend" }
gol-frontend = { path = "crates/gol-frontend" }

